[features]
seeds = false
skip-lint = false
[programs.devnet]
gratie_solana = "FmG2zTeSd4rStaj6FD9W8WipbXGjDyF3e3btXTqBFbky"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mucks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
